name: islamy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#202020"
  image: assets/images/islami_logo_splash.png
  branding: assets/images/islami_branding.png
  android_12:
    color: "#202020"
    image: assets/images/islami_logo_android_12.png
    branding: assets/images/islami_branding.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
